Хедер, 3я секция, футер без адаптива
Sladkiy-ruletik/Novgorodformacia pull request #10
Opened 2024-11-03 16:44 UTC by Sladkiy-ruletik

2024-11-05 15:49 UTC, TChebun requested changes

2024-11-05 15:49 UTC, TChebun commented on assets/styles/style.sass
> +  &__conteiner
Выровнять контейнер посередине. контейнер должен быть поверх изображения, а не отдельно.

2024-11-05 15:49 UTC, TChebun commented on assets/styles/style.sass
> +  &__wrapper
Выровнять посередине

2024-11-05 15:49 UTC, TChebun commented on assets/styles/style.sass
>    &__link
Добавить ссылкам transition для плавности

2024-11-05 15:49 UTC, TChebun commented on assets/styles/style.sass
> +  &__container
Выровнять контейнер посередине

2024-11-05 15:49 UTC, TChebun commented on assets/styles/style.sass
> +  &__content
Где-то дублируется footer__content (css - 1024 строчка)

2024-11-07 17:53 UTC, Sladkiy-ruletik commented on assets/styles/style.sass
> +  &__conteiner
Получается, мне нужно изменить структуру кода? убрать &__block между контейнером и изображением?

2024-11-07 17:54 UTC, Sladkiy-ruletik commented on assets/styles/style.sass
>    &__link
Добавила

2024-11-07 18:28 UTC, Sladkiy-ruletik commented on assets/styles/style.sass
> +  &__wrapper
Выравнивать при помоши flexbox?
тогда миссия встает справа от истории

2024-11-07 18:57 UTC, Sladkiy-ruletik commented on assets/styles/style.sass
> +  &__content
там былая старая версия футера, я ее удалила, но этот футер почему-то словно неотображается
Может в расположении дело?

2024-11-10 10:34 UTC, TChebun requested changes

2024-11-10 10:34 UTC, TChebun commented on assets/styles/style.sass
> +    margin: 0
margin: 0 auto;

2024-11-10 10:34 UTC, TChebun commented on assets/styles/style.sass
> +    margin: 0
margin: 0 auto;

2024-11-10 10:34 UTC, TChebun commented on assets/styles/style.sass
>      font-family: 'Fira Sans'
Убрать из .history__blok padding-top, перенести верхний отступ в history, выставить согласно дизайну, добавить нижний отступ history согласно дизайну

2024-11-10 10:34 UTC, TChebun commented on assets/styles/style.sass
>    background-color: $primary-color
Добавить .footer внутренние отступы согласно дизайну

2024-12-28 12:23 UTC, TChebun approved these changes

2024-12-28 12:23 UTC, merged