edit advantages form media
Sladkiy-ruletik/Novgorodformacia pull request #8
Opened 2024-10-30 17:24 UTC by Jenikafacet

Внесла коррективы в секции "Преимущества", "Форма" (в том числе контейнер с шириной 1590px), коррективы в медиа-запросах.

2024-10-31 05:59 UTC, Jenikafacet commented
> Внесла коррективы в секции "Преимущества", "Форма" (в том числе контейнер с шириной 1590px), коррективы в медиа-запросах.

2024-10-31 08:34 UTC, TChebun requested changes

2024-10-31 08:34 UTC, TChebun commented on assets/styles/style.css
> +.form__wrapper::after {
Before и after лучше прицепить на .form, а не .form__wrapper, тогда не придется множить безумные формулы, а просто поставить width: 100%, и он займет всю ширину

2024-10-31 08:34 UTC, TChebun commented on assets/styles/style.sass
> +@media screen and (max-width: 1920px)
У нас есть контейнер, который займет нужную ширину, @media screen and (max-width: 1920px) не нужно писать, потому что тогда мы ограничиваем страницы. А если у человека суперширокоформатник?

2024-10-31 08:34 UTC, TChebun commented on assets/styles/style.css
> +  background-position: cover;
background-size, а не position

2024-10-31 08:34 UTC, TChebun commented on assets/styles/style.sass
>    &__wrapper::before
Before и after лучше прицепить на .form, а не .form__wrapper, тогда не придется множить безумные формулы, а просто поставить width: 100%, и он займет всю ширину

2024-11-01 15:33 UTC, TChebun approved these changes

2024-11-01 15:33 UTC, merged