скорректированы стили для экрана 1 и 2, на 1 экран добавлена картинка…
Sladkiy-ruletik/Novgorodformacia pull request #9
Opened 2024-10-31 17:14 UTC by by-anna-marso

… флюид

2024-10-31 17:41 UTC, TChebun requested changes

2024-10-31 17:41 UTC, TChebun commented on assets/styles/style.sass
> +//Первый и второй экран миксин
Перепроверить sass, где-то на 689 строке идут повторения кода, которые перебьют этот.

2024-10-31 17:41 UTC, TChebun commented on assets/styles/style.sass
> +  min-height: 1038px
min-height убираем, как и паддинги

2024-10-31 17:41 UTC, TChebun commented on assets/styles/style.sass
> +  position: absolute
делаем картинку обычной, без абсолютного позиционирования

2024-10-31 17:41 UTC, TChebun commented on assets/styles/style.sass
> +.hero-text-container
Абсолютно позиционируем этот блок, а не картинку

2024-10-31 17:41 UTC, TChebun commented on assets/styles/style.sass
> +.about-section
Перепроверить адаптив всей секции, ломается.

2024-10-31 17:49 UTC, by-anna-marso commented on assets/styles/style.sass
> +//Первый и второй экран миксин
с 689 был дубль стилей для 1 и 2 экрана , удалено.

2024-10-31 17:59 UTC, by-anna-marso commented on assets/styles/style.sass
> +.hero-text-container
done

2024-10-31 18:00 UTC, by-anna-marso commented on assets/styles/style.sass
> +  position: absolute
done

2024-10-31 18:01 UTC, by-anna-marso commented on assets/styles/style.sass
> +  min-height: 1038px
done

2024-10-31 20:00 UTC, TChebun requested changes

2024-10-31 20:00 UTC, TChebun commented on assets/styles/style.css
> +  margin-left: 205px;
в адаптив вылезло

2024-10-31 20:00 UTC, TChebun commented on assets/styles/style.css
> +@media (max-width: 575px) {
Убираем

2024-10-31 20:00 UTC, TChebun commented on assets/styles/style.sass
>    height: 100%
при уменьшении экрана уменьшить картинку, высоту до 500px например. и вуальку тоже

2024-10-31 20:00 UTC, TChebun commented on assets/styles/style.css
> -  min-height: 1038px;
из .hero-content-wrapper и hero-section убрать min-height

2024-10-31 20:00 UTC, TChebun commented on assets/styles/style.css
>  .hero-background {
убираем абсолют, картинка обычная, блок с текстом на нее абсолютом

2024-10-31 20:00 UTC, TChebun commented on assets/styles/style.css
>  .about-image {
в адаптиве, когда займет всю площадь экрана - убрать радиус с угла

2024-10-31 20:07 UTC, by-anna-marso commented on assets/styles/style.css
> +  margin-left: 205px;
done

2024-10-31 20:07 UTC, by-anna-marso commented on assets/styles/style.css
> +@media (max-width: 575px) {
done

2024-10-31 20:08 UTC, by-anna-marso commented on assets/styles/style.css
> -  min-height: 1038px;
done

2024-10-31 20:21 UTC, by-anna-marso commented on assets/styles/style.sass
>    height: 100%
done

2024-10-31 21:02 UTC, by-anna-marso commented on assets/styles/style.css
>  .hero-background {
done

2024-10-31 21:02 UTC, by-anna-marso commented on assets/styles/style.css
>  .about-image {
нужна картинка оригинал без радиуса

2024-11-01 20:58 UTC, TChebun approved these changes

2024-11-01 20:58 UTC, merged